repos:
  - repo: https://github.com/google/keep-sorted
    rev: v0.8.0
    hooks:
      - id: keep-sorted
  - repo: local
    hooks:
      - id: update-requirements
        name: update-requirements
        entry: python ./bin/update_requirements.py
        language: system
        files: ^requirements\.in$
        pass_filenames: false
      - id: update-ide-paths
        name: update-ide-paths
        entry: python ./bin/update_ide_paths.py
        language: system
        files: ^requirements\.txt$
        pass_filenames: false
      - id: buildifier
        name: buildifier
        entry: python ./bin/buildifier.py -lint fix -mode fix --
        language: system
        files: (^|/)(BUILD\.bazel|MODULE\.bazel|.*\.bzl)$
